# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

CRATES="
	aho-corasick@0.7.20
	android_system_properties@0.1.5
	anyhow@1.0.68
	autocfg@1.1.0
	base64@0.13.1
	bitflags@1.3.2
	bumpalo@3.11.1
	cc@1.0.78
	cfg-if@1.0.0
	chrono@0.4.23
	clap@4.0.32
	clap_derive@4.0.21
	clap_lex@0.3.0
	codespan-reporting@0.11.1
	core-foundation-sys@0.8.3
	cxx-build@1.0.86
	cxx@1.0.86
	cxxbridge-flags@1.0.86
	cxxbridge-macro@1.0.86
	darling@0.14.2
	darling_core@0.14.2
	darling_macro@0.14.2
	either@1.8.0
	enumset@1.0.12
	enumset_derive@0.6.1
	env_logger@0.10.0
	errno-dragonfly@0.1.2
	errno@0.2.8
	fnv@1.0.7
	hashbrown@0.12.3
	heck@0.4.0
	hermit-abi@0.2.6
	hex@0.4.3
	humantime@2.1.0
	iana-time-zone-haiku@0.1.1
	iana-time-zone@0.1.53
	ident_case@1.0.1
	indexmap@1.9.2
	indoc@1.0.8
	io-lifetimes@1.0.3
	is-terminal@0.4.2
	itertools@0.10.5
	itoa@1.0.5
	js-sys@0.3.60
	libc@0.2.139
	libusb1-sys@0.6.4
	link-cplusplus@1.0.8
	linux-raw-sys@0.1.4
	log@0.4.17
	memchr@2.5.0
	minimal-lexical@0.2.1
	nom@7.1.2
	num-integer@0.1.45
	num-traits@0.2.15
	once_cell@1.17.0
	os_str_bytes@6.4.1
	pkg-config@0.3.26
	proc-macro-error-attr@1.0.4
	proc-macro-error@1.0.4
	proc-macro2@1.0.49
	quote@1.0.23
	regex-syntax@0.6.28
	regex@1.7.1
	rusb@0.9.1
	rustix@0.36.6
	rustversion@1.0.11
	ryu@1.0.12
	scratch@1.0.3
	serde@1.0.152
	serde_derive@1.0.152
	serde_json@1.0.91
	serde_with@2.2.0
	serde_with_macros@2.2.0
	serde_yaml@0.9.16
	strsim@0.10.0
	strum@0.24.1
	strum_macros@0.24.3
	syn@1.0.107
	termcolor@1.1.3
	time-core@0.1.0
	time-macros@0.2.6
	time@0.3.17
	unicode-ident@1.0.6
	unicode-width@0.1.10
	unsafe-libyaml@0.2.5
	vcpkg@0.2.15
	version_check@0.9.4
	wasm-bindgen-backend@0.2.83
	wasm-bindgen-macro-support@0.2.83
	wasm-bindgen-macro@0.2.83
	wasm-bindgen-shared@0.2.83
	wasm-bindgen@0.2.83
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.42.0
	windows_aarch64_gnullvm@0.42.0
	windows_aarch64_msvc@0.42.0
	windows_i686_gnu@0.42.0
	windows_i686_msvc@0.42.0
	windows_x86_64_gnu@0.42.0
	windows_x86_64_gnullvm@0.42.0
	windows_x86_64_msvc@0.42.0
"

inherit cargo

DESCRIPTION="Command-line tool for programming ch57x keyboard"
HOMEPAGE="https://github.com/kriomant/ch57x-keyboard-tool"
SRC_URI="
	https://github.com/kriomant/ch57x-keyboard-tool/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 MIT Unicode-DFS-2016"
SLOT="0"
KEYWORDS="~amd64"

DEPEND="virtual/libusb:1"
RDEPEND="${DEPEND}"
S="${WORKDIR}/${PN}-${PV}"

src_install() {
    cargo_src_install
    dobin target/release/${PN}
}
