ACCEPT_KEYWORDS="~amd64"

MAKEOPTS="-j16 -l17"

USE="
${USE}
alsa
cups
flac
egl
harfbuzz
icu
jpeg
opengl
pdf
pipewire
pulseaudio
vulkan
wayland
X
zeroconf
"

FEATURES="${FEATURES} buildpkg -binpkg-signing -binpkg-request-signature"
PKGDIR="/var/cache/binpkgs"
BINPKG_FORMAT="gpkg"
