MAKEOPTS="-j16 -l17"

FEATURES="${FEATURES} getbinpkg -binpkg-request-signature"
PORTAGE_BINHOST="http://192.168.4.78:8080"
BINPKG_FORMAT="gpkg"

USE="
${USE}
cryptsetup
egl
flac
harfbuzz
jpeg
opengl
pipewire
pulseaudio
vulkan
wayland
X
zeroconf
"
