user nginx nginx;
worker_processes auto;
include modules-enabled/*.conf;

events {
	# NGINX refuses to start if the 'events' section is not present. Yet,
	# NGINX does not seem to care whether this section is non-empty.
}

http {
	include       mime.types.nginx;
	types_hash_max_size  4096;
	    default_type  application/octet-stream;

	    server {
	        listen 8080;
	        server_name _;

	        location / {
	            root /var/cache/binpkgs;
	            autoindex on;

	            # Ensure gpkg is served correctly
	            types {
	                application/gzip gpkg;
	            }
	        }
	    }
		}
