COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

ACCEPT_KEYWORDS="~amd64"

# NOTE: This stage was built with the bindist USE flag enabled
FEATURES="${FEATURES} parallel-fetch"
FEATURES="${FEATURES} getbinpkg"
FEATURES="${FEATURES} binpkg-request-signature"

LC_MESSAGES=C.UTF-8

ACCEPT_LICENSE="*"

USE="
dbus
dist-kernel
dracut
elogind
networkmanager
zstd
"
